# Generated by Django 4.2.14 on 2024-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_password_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="EMP101", max_length=255, unique=True),
        ),
    ]
